<?php

namespace ContainerXLHpKdf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PCSGpn6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PCSGpn6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PCSGpn6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ClassroomController::addC' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ClassroomController::deleteC' => ['privates', '.service_locator.96w2VfZ', 'get_ServiceLocator_96w2VfZService', true],
            'App\\Controller\\ClassroomController::listC' => ['privates', '.service_locator.OVxUqTr', 'get_ServiceLocator_OVxUqTrService', true],
            'App\\Controller\\ClassroomController::updateC' => ['privates', '.service_locator.96w2VfZ', 'get_ServiceLocator_96w2VfZService', true],
            'App\\Controller\\UserController::addU' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\UserController::deleteU' => ['privates', '.service_locator.NrOzefX', 'get_ServiceLocator_NrOzefXService', true],
            'App\\Controller\\UserController::listU' => ['privates', '.service_locator.cqiVNiN', 'get_ServiceLocator_CqiVNiNService', true],
            'App\\Controller\\UserController::updateU' => ['privates', '.service_locator.NrOzefX', 'get_ServiceLocator_NrOzefXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ClassroomController:addC' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ClassroomController:deleteC' => ['privates', '.service_locator.96w2VfZ', 'get_ServiceLocator_96w2VfZService', true],
            'App\\Controller\\ClassroomController:listC' => ['privates', '.service_locator.OVxUqTr', 'get_ServiceLocator_OVxUqTrService', true],
            'App\\Controller\\ClassroomController:updateC' => ['privates', '.service_locator.96w2VfZ', 'get_ServiceLocator_96w2VfZService', true],
            'App\\Controller\\UserController:addU' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\UserController:deleteU' => ['privates', '.service_locator.NrOzefX', 'get_ServiceLocator_NrOzefXService', true],
            'App\\Controller\\UserController:listU' => ['privates', '.service_locator.cqiVNiN', 'get_ServiceLocator_CqiVNiNService', true],
            'App\\Controller\\UserController:updateU' => ['privates', '.service_locator.NrOzefX', 'get_ServiceLocator_NrOzefXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ClassroomController::addC' => '?',
            'App\\Controller\\ClassroomController::deleteC' => '?',
            'App\\Controller\\ClassroomController::listC' => '?',
            'App\\Controller\\ClassroomController::updateC' => '?',
            'App\\Controller\\UserController::addU' => '?',
            'App\\Controller\\UserController::deleteU' => '?',
            'App\\Controller\\UserController::listU' => '?',
            'App\\Controller\\UserController::updateU' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClassroomController:addC' => '?',
            'App\\Controller\\ClassroomController:deleteC' => '?',
            'App\\Controller\\ClassroomController:listC' => '?',
            'App\\Controller\\ClassroomController:updateC' => '?',
            'App\\Controller\\UserController:addU' => '?',
            'App\\Controller\\UserController:deleteU' => '?',
            'App\\Controller\\UserController:listU' => '?',
            'App\\Controller\\UserController:updateU' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
