<?php

namespace ContainerXLHpKdf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_96w2VfZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.96w2VfZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.96w2VfZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'c' => ['privates', 'App\\Repository\\ClassroomRepository', 'getClassroomRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'c' => 'App\\Repository\\ClassroomRepository',
            'doctrine' => '?',
        ]);
    }
}
