<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXLHpKdf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXLHpKdf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXLHpKdf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXLHpKdf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXLHpKdf\App_KernelDevDebugContainer([
    'container.build_hash' => 'XLHpKdf',
    'container.build_id' => 'ba63a250',
    'container.build_time' => 1761259633,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXLHpKdf');
